// Generated by https://quicktype.io

export interface NewTrabajadorResponse {
    nombre: string;
    email: string;
    telefono: string;
    username: string;
    password: string;
    puesto: string;
    fechaNacimiento: string;
}
