// Generated by https://quicktype.io

export interface CategoryProductResponse {
    nombre: string;
    productos: Producto[];
}

export interface Producto {
    nombre: string;
    imagen: string;
    descripcion: string;
    precio: number;
    tags: string[];
}
