// Generated by https://quicktype.io

export interface EditLoggedUserResponse {
    nombre:    string;
    email:     string;
    telefono:  string;
    avatar:    string;
    direccion: string;
    codPostal: string;
    poblacion: string;
}
