// Generated by https://quicktype.io

export interface ListOrderAdminResponse {
    id:           string;
    fecha:        string;
    estadoPedido: string;
    cliente:      string;
    repartidor:   string;
    cocinero:     string;
}

