// Generated by https://quicktype.io

export interface LoggedUserDetailResponse {
    id:       string;
    username: string;
    nombre:   string;
    email:    string;
    telefono: string;
    avatar:   null;
    roles:    string[];
}
