// Generated by https://quicktype.io

export interface LoggedUserAllDetailResponse {
    id:        string;
    nombre:    string;
    email:     string;
    avatar:    string;
    direccion: string;
    codPostal: string;
    poblacion: string;
    puntos:    number;
    pedidos:   Pedido[];
}

export interface Pedido {
    id:           string;
    fecha:        string;
    estadoPedido: string;
    importeTotal: number;
}
