// Generated by https://quicktype.io

export interface TrabajadorLoggedResponse {
    id: string;
    nombre: string;
    email: string;
    telefono: string;
    username: string;
    puesto: string;
    rol: string;
    fechaNacimiento: string;
}
