// Generated by https://quicktype.io

export interface MenuResponse {
    id:           string;
    nombre:       string;
    imagen:       string;
    descripcion:  string;
    precio:       number;
    precioOferta: number;
    tags:         string[];
    categoria:    Categoria;
}

export interface Categoria {
    id:     string;
    nombre: string;
}
