// Generated by https://quicktype.io

export interface OrderListCocineroResponse {
    content:          OrderCocinero[];
    pageable:         Pageable;
    last:             boolean;
    totalPages:       number;
    totalElements:    number;
    size:             number;
    number:           number;
    sort:             Sort;
    first:            boolean;
    numberOfElements: number;
    empty:            boolean;
}

export interface OrderCocinero {
    id:           string;
    fecha:        string;
    estadoPedido: string;
    lineasPedido: LineasPedido[];
}

export interface LineasPedido {
    producto: string;
    cantidad: number;
}

export interface Pageable {
    pageNumber: number;
    pageSize:   number;
    sort:       Sort;
    offset:     number;
    paged:      boolean;
    unpaged:    boolean;
}

export interface Sort {
    empty:    boolean;
    sorted:   boolean;
    unsorted: boolean;
}
