// Generated by https://quicktype.io

export interface OrderDetailsResponse {
    id:           string;
    fecha:        string;
    cliente:      string;
    estadoPedido: string;
    ln:           Ln[];
    importe:      number;
}

export interface Ln {
    producto: string;
    precioUnitario: number;
    cantidad: number;
}

