// Generated by https://quicktype.io

export interface PedidoDetailResponse {
    id:           string;
    direccion:    string;
    telefono:     string;
    estadoPedido: string;
    horaLlegada:  string;
    lineasPedido: LineasPedido[];
    total:        number;
}

export interface LineasPedido {
    nombreProducto:    string;
    cantidadProductos: number;
    precioUnit:        number;
    subtotal:          number;
}
