// Generated by https://quicktype.io

export interface ProductRowResponse {
    id:          string;
    nombre:      string;
    imagen:      string;
    descripcion: string;
    precio:      number;
}
